registro/config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#show'
  
  get "loginalunno" => "sessionealunno#new"
  get "registrazionealunno" => "alunni#new"
  post "sessionealunno/create"
  get "logoutalunno" => "sessionealunno#destroy"
  get "menualunno" => "alunni#menu"
  get "elenco" => 'alunni#elenco'
  get "assenzealunno" => "assenze/:alunno_id", to: "assenze#index"
  get "notedisciplinarialunno" => "notedisciplinari/:alunno_id", to: "notedisciplinari#index"
  get "votialunno" => "voti/:alunno_id", to: "voti#index"

  get "logindocenza" => "sessionedocenza#new"
  get "registrazionedocenza" => "docenze#new"
  post "sessionedocenza/create"
  get "logoutdocenza" => "sessionedocenza#destroy"
  get "menudocenza" => "docenze#menu"

  get "loginamministrazione" => "sessioneamministrazione#new"
  get "registrazioneamministrazione" => "amministrazioni#new"
  post "sessioneamministrazione/create"
  get "logoutamministrazione" => "sessioneamministrazione#destroy"
  get "menuamministrazione" => "amministrazioni#menu"

  get "doc_sez_mat" => "docenza_sezione_materie/:sezione_id", to: 'docenza_sezione_materie#index'
  get "nuovoinsegnamento" => "docenza_sezione_materie#nuovoinsegnamento"
  post "/alunno_attivitaextras/new"
	

  resources :alunno_attivitaextras

  resources :voti

  resources :sezioni

  resources :notedisciplinari

  resources :materie

  resources :compiti

  resources :circolari

  resources :attivitaextras

  resources :assenze

  resources :docenze

  resources :amministrazioni

  resources :alunni

  resources :docenza_sezione_materie

  resources :alunni do
    member do
      get :confirm_email
    end
  end

  resources :docenze do
    member do
      get :confirm_email
    end
  end

  resources :amministrazioni do
    member do
      get :confirm_email
    end
  end

end

registro/app/controllers/docenze_controller.rb
class DocenzeController < ApplicationController
  before_action :set_docenza, only: [:show, :edit, :update, :destroy]
  before_filter :is_permitted, only: [:edit, :update, :destroy]

  def is_permitted
    if session[:role] == "alunno"
      redirect_to :back, :alert => "Operazione non permessa"
    end
  end

  def confirm_email
    docenza = Docenza.find_by_confirm_token(params[:id])
    if docenza
      docenza.email_activate
      flash[:success] = "Welcome! Your email has been confirmed.
      Please sign in to continue."
      redirect_to logindocenza_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  def menu
  end

  # GET /docenze
  # GET /docenze.json
  def index
    @docenze = Docenza.all
  end

  # GET /docenze/1
  # GET /docenze/1.json
  def show
  end

  # GET /docenze/new
  def new
    @docenza = Docenza.new
  end

  # GET /docenze/1/edit
  def edit
  end

  # POST /docenze
  # POST /docenze.json
  def create
    @docenza = Docenza.new(docenza_params)

    respond_to do |format|
      if @docenza.save
        DocenzaMailer.registration_confirmation(@docenza).deliver_now
        format.html { redirect_to @docenza, notice: 'Docenza was successfully created.' }
        format.json { render :show, status: :created, location: @docenza }
      else
        format.html { render :new }
        format.json { render json: @docenza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docenze/1
  # PATCH/PUT /docenze/1.json
  def update
    respond_to do |format|
      @docenza.user=session[:role]
      if session[:role] != "docenza"
		    docenza_params.delete(:email)
		    docenza_params.delete(:password)
		    docenza_params.delete(:password_confirmation)
      end
      if @docenza.update(docenza_params)
        format.html { redirect_to @docenza, notice: 'Docenza was successfully updated.' }
        format.json { render :show, status: :ok, location: @docenza }
      else
        format.html { render :edit }
        format.json { render json: @docenza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docenze/1
  # DELETE /docenze/1.json
  def destroy
    @docenza.destroy
    respond_to do |format|
      format.html { redirect_to docenze_url, notice: 'Docenza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docenza
      @docenza = Docenza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docenza_params
      params.require(:docenza).permit(:cf, :nome, :cognome, :indirizzo, :cittaresidenza, :cittanascita, :datanascita, :curriculum, :email, :password, :password_confirmation)
    end
end

registro/app/helpers/docenze_helper.rb
module DocenzeHelper
end

registro/app/views/docenze/_form.html.erb
<%= form_for(@docenza) do |f| %>
  <% if @docenza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docenza.errors.count, "error") %> prohibited this docenza from being saved:</h2>

      <ul>
      <% @docenza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <% if session[:role] == 'docenza' || session[:role]==nil %>
  <h2>Inserire dati per la registrazione:</h2>

  <div class="field">
    <%= f.label :"email" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :"conferma Password" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
<% end %>

  <h2>Inserire dati personali:</h2>

  <div class="field">
    <%= f.label :"c"%><%= f.label :"f"%><br>
    <%= f.text_field :cf %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cognome %><br>
    <%= f.text_field :cognome %>
  </div>
  <div class="field">
    <%= f.label :indirizzo %><br>
    <%= f.text_field :indirizzo %>
  </div>
  <div class="field">
    <%= f.label :"città di residenza" %><br>
    <%= f.text_field :cittaresidenza %>
  </div>
  <div class="field">
    <%= f.label :"città di nascita" %><br>
    <%= f.text_field :cittanascita %>
  </div>
  <div class="field">
    <%= f.label :"data di nascita" %><br>
    <%= f.date_select :datanascita , order: [:day, :month, :year], :use_month_names => ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Gugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre','Dicembre'], start_year: Date.today.year, end_year: Date.today.year - 100 %>
  </div>
    <div class="field">
    <%= f.label :curriculum %><br>
    <%= f.text_field :curriculum %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.submit "Invio", :class => 'button', :style=>'background:#FFE0B2'%>
  </div>
<% end %>

registro/app/views/docenze/edit.html.erb
<!DOCTYPE html>
<html>
<body style="background:#FFA726;">
	<h1 style="text-align:center;">Modifica Dati</h1></div>
    <%= render 'form' %>
</body>
<%= link_to 'Show', @docenza %> |
<%= link_to 'Back', docenze_path %>
</html>

registro/app/views/docenze/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elenco Docenti</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<p id="notice"><%= notice %></p>

<body style="background:#FFA726;">
    <div class="col-md-12" style="text-align:center;">
        <h1> Elenco Docenti</h1></div>
    <div class="col-md-12">
        <div class="table-responsive", align="center">
			<table class="table", style="border-collapse:collapse;">

              <thead>
				    <tr>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>CF</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Nome</span>
					  </th>

					  <th style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Cognome</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Indirizzo</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Città di residenza</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Città di nascita</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Data di nascita</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Curriculum Vitae</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Email</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Mostra</span>
					  </th>
					  <% if session[:role] != 'alunno' && userlogged_in? %>  
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Modifica</span>
					  </th>
					  <%end%>
					  <% if session[:role] == 'amministrazione' && userlogged_in? %>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Elimina</span>
					  </th>
					  <%end%>
					</tr>					
		<tbody>
			<% @docenze.each do |docenza| %>
			  <tr>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.cf %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.nome %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.cognome %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.indirizzo %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.cittaresidenza %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.cittanascita %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.datanascita %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><a href="<%= docenza.curriculum %>">curriculum</a></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= docenza.email %></td>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Show', docenza, :style=>"color:black;"%></td>
				<% if session[:role] != 'alunno' && userlogged_in? %>       
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Edit', edit_docenza_path(docenza), :style=>"color:black;" %></td>
				<%end%>
				<% if session[:role] == 'amministrazione' && userlogged_in? %>
				<td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Destroy', docenza, :style=>"color:black;" , method: :delete, data: { confirm: 'Sei Sicuro?' } %></td>
			    <%end%>
			  </tr>
			<% end %>
   	   </tbody>
</table>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

registro/app/views/docenze/menu.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>menuAl</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body style="background:#FFA726;">
    <div class="col-md-12">
        <h1> </h1>
    </div>
    <div class="col-md-12">
        <h1 style="text-align:center;">Menu </h1>
        <h1> </h1>
    </div>
    <div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Compiti in classe</button>".html_safe, compiti_path, :style=>"color:black" %>
        <h3> </h3>
    </div>
    <div class="col-md-12" style="text-align:center;">		
        <%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Attività extrascolastiche</button>".html_safe, attivitaextras_path, :style=>"color:black" %>
        <h3> </h3>
    </div>
    <div class="col-md-12" style="text-align:center;">
         <%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Inserisci voto</button>".html_safe, voti_path, :style=>"color:black" %>
        <h3> </h3>
    </div>
    <div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Visualizza circolari</button>".html_safe, circolari_path, :style=>"color:black" %>
		<h3> </h3>
    </div>

	<div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Inserisci nota</button>".html_safe, notedisciplinari_path, :style=>"color:black" %>
		<h3> </h3>
    </div>

	<div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Elenco sezioni</button>".html_safe, sezioni_path, :style=>"color:black" %>
		<h3> </h3>
    </div>


    <div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Visualizza profilo</button>".html_safe, docenza_path(current_user.id), :style=>"color:black" %>
        <h1> </h1>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

registro/app/views/docenze/new.html.erb
<!DOCTYPE html>
<html>
<body style="background:#FFA726;">
	<h1 style="text-align:center;">Nuovo Componente del corpo Docenti</h1></div>
    <%= render 'form' %>
</body>
<%= link_to 'Back', docenze_path %>
</html>

registro/app/views/docenze/show.html.erb
<!DOCTYPE html>
<html>
<body style="background:#FFA726;">
<p id="notice"><%= notice %></p>

<p>
  <h1 style="text-align:center;">Dati Registrati </h1>
  <h2>Dati Personali </h2>
  <strong>CF:</strong>
  <%= @docenza.cf %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @docenza.nome %>
</p>

<p>
  <strong>Cognome:</strong>
  <%= @docenza.cognome %>
</p>

<p>
  <strong>Indirizzo:</strong>
  <%= @docenza.indirizzo %>
</p>

<p>
  <strong>Città di residenza:</strong>
  <%= @docenza.cittaresidenza %>
</p>

<p>
  <strong>Città di nascita:</strong>
  <%= @docenza.cittanascita %>
</p>

<p>
  <strong>Data di nascita:</strong>
  <%= @docenza.datanascita %>
</p>

<p>
  <strong>Curriculum:</strong>
  <a href="<%= @docenza.curriculum %>">Link al curriculum</a>
</p>

<p>
  <h2>Dati Registrazione </h2>
  <strong>Email:</strong>
  <%= @docenza.email %>
</p>

<p>
  <strong>Password: *******</strong>
  <%= @docenza.password %>
</p>


<% if session[:role] != 'alunno' && userlogged_in? %>
  <%= link_to 'Edit', edit_docenza_path(@docenza) %>
  <%= link_to 'Destroy', @docenza, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
  <%= link_to 'Login', logindocenza_path %>
<% end %>