registro/config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#show'
  
  get "loginalunno" => "sessionealunno#new"
  get "registrazionealunno" => "alunni#new"
  post "sessionealunno/create"
  get "logoutalunno" => "sessionealunno#destroy"
  get "menualunno" => "alunni#menu"
  get "elenco" => 'alunni#elenco'
  get "assenzealunno" => "assenze/:alunno_id", to: "assenze#index"
  get "notedisciplinarialunno" => "notedisciplinari/:alunno_id", to: "notedisciplinari#index"
  get "votialunno" => "voti/:alunno_id", to: "voti#index"

  get "logindocenza" => "sessionedocenza#new"
  get "registrazionedocenza" => "docenze#new"
  post "sessionedocenza/create"
  get "logoutdocenza" => "sessionedocenza#destroy"
  get "menudocenza" => "docenze#menu"

  get "loginamministrazione" => "sessioneamministrazione#new"
  get "registrazioneamministrazione" => "amministrazioni#new"
  post "sessioneamministrazione/create"
  get "logoutamministrazione" => "sessioneamministrazione#destroy"
  get "menuamministrazione" => "amministrazioni#menu"

  get "doc_sez_mat" => "docenza_sezione_materie/:sezione_id", to: 'docenza_sezione_materie#index'
  get "nuovoinsegnamento" => "docenza_sezione_materie#nuovoinsegnamento"
  post "/alunno_attivitaextras/new"
	

  resources :alunno_attivitaextras

  resources :voti

  resources :sezioni

  resources :notedisciplinari

  resources :materie

  resources :compiti

  resources :circolari

  resources :attivitaextras

  resources :assenze

  resources :docenze

  resources :amministrazioni

  resources :alunni

  resources :docenza_sezione_materie

  resources :alunni do
    member do
      get :confirm_email
    end
  end

  resources :docenze do
    member do
      get :confirm_email
    end
  end

  resources :amministrazioni do
    member do
      get :confirm_email
    end
  end

end

registro/app/controllers/sezioni_controller.rb
class SezioniController < ApplicationController
  before_action :set_sezione, only: [:show, :edit, :update, :destroy]
  before_filter :is_permitted, only: [:new, :edit, :update, :destroy]

  def is_permitted
    if session[:role] != "amministrazione"
      redirect_to :back, :alert => "Operazione non permessa"
    end
  end

  # GET /sezioni
  # GET /sezioni.json
  def index
    @sezioni = Sezione.all
  end

  # GET /sezioni/1
  # GET /sezioni/1.json
  def show
  end

  # GET /sezioni/new
  def new
    @sezione = Sezione.new
  end

  # GET /sezioni/1/edit
  def edit
  end

  # POST /sezioni
  # POST /sezioni.json
  def create
    @sezione = Sezione.new(sezione_params)

    respond_to do |format|
      if @sezione.save
        format.html { redirect_to @sezione, notice: 'Sezione was successfully created.' }
        format.json { render :show, status: :created, location: @sezione }
      else
        format.html { render :new }
        format.json { render json: @sezione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sezioni/1
  # PATCH/PUT /sezioni/1.json
  def update
    respond_to do |format|
      if @sezione.update(sezione_params)
        format.html { redirect_to @sezione, notice: 'Sezione was successfully updated.' }
        format.json { render :show, status: :ok, location: @sezione }
      else
        format.html { render :edit }
        format.json { render json: @sezione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sezioni/1
  # DELETE /sezioni/1.json
  def destroy
    @sezione.destroy
    respond_to do |format|
      format.html { redirect_to sezioni_url, notice: 'Sezione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sezione
      @sezione = Sezione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sezione_params
      params.require(:sezione).permit(:lettera, :numero)
    end
end

registro/app/helpers/sezioni_helper.rb
module SezioniHelper
end

registro/app/views/sezioni/_form.html.erb
<%= form_for(@sezione) do |f| %>
  <% if @sezione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sezione.errors.count, "error") %> prohibited this sezione from being saved:</h2>

      <ul>
      <% @sezione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Lettera %><br>
    <%= f.text_field :lettera %>
  </div>
  <div class="field">
    <%= f.label :Numero %><br>
    <%= f.number_field :numero %>
  </div>
   <div class="actions">
    <%= f.submit "Invio", :class => 'button', :style=>'background:#FFE0B2'%>
  </div>
<% end %>

registro/app/views/sezioni/edit.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifica Sezione</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body style="background:#FFA726;">
    <div class="col-md-12">
        <h1 style="text-align:center;">Modifica Sezione</h1></div>
    <div class="col-md-12", align="center">
		<%= render 'form' %>
    </div>
		
    <div class="col-md-12" , align="center">
		<%= link_to 'Modifica elenco alunni', elenco_path(:sezione_id => @sezione.id) %> |
    
    <%= link_to 'Show', @sezione, :style=>"color:trasparent" %> |
	<%= link_to 'Back', sezioni_path, :style=>"color:trasparent"  %>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    </div>
</body>

</html>

registro/app/views/sezioni/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elenco Sezioni</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>
<p id="notice"><%= notice %></p>

<body style="background:#FFA726;">
    <div class="col-md-12" style="text-align:center;">
        <h1> Elenco Sezioni</h1></div>
    <div class="col-md-12">
        <div class="table-responsive", align="center">
			<table class="table", style="border-collapse:collapse;">

              <thead>
    <tr>
	  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Lettera</span>
	  </th>
	  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Numero</span>
	  </th>		
	  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Mostra</span>
	  </th>
	  <% if session[:role] == 'amministrazione' && userlogged_in? %>
	  
	  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Modifica</span>
	  </th>
	  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Elimina</span>
	  </th>	
	  <%end%>  
    </tr>
  </thead>

  <tbody>
    <% @sezioni.each do |sezione| %>
      <tr>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= sezione.lettera %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= sezione.numero %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Show', sezione , :style=>"color:trasparent;" %></td>
	<% if session[:role] == 'amministrazione' && userlogged_in? %>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Edit', edit_sezione_path(sezione) , :style=>"color:trasparent;" %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Destroy', sezione , :style=>"color:trasparent;", method: :delete, data: { confirm: 'Sei Sicuro?' } %></td>
	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<% if session[:role] == 'amministrazione' && userlogged_in? %>
<br>

<%= link_to 'Visualizza alunni non assegnati', elenco_path(:sezione_id => nil) , :style=>"color:trasparent;" %>

<br><br>

<%= link_to 'Nuova Sezione', new_sezione_path , :style=>"color:trasparent;" %>
<% end %>

   	   </tbody>
</table>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

registro/app/views/sezioni/new.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuova Sezione</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body style="background:#FFA726;">
    <div class="col-md-12">
        <h1 style="text-align:center;">Inserimento Nuova Sezione</h1></div>
    <div class="col-md-12", align="center">
		<%= render 'form' %>
    </div>
		
    <div class="col-md-12" , align="center">
		<%= link_to 'Modifica elenco alunni', elenco_path(:sezione_id => @sezione.id) %> |
    
	<%= link_to 'Back', sezioni_path, :style=>"color:trasparent"  %>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    </div>
</body>

</html>

registro/app/views/sezioni/show.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mostra Sezione</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body style="background:#FFA726;">
    <div class="col-md-12", align="center">
        <p id="notice"><%= notice %></p>

<p>
  <strong>Lettera:</strong>
  <%= @sezione.lettera %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @sezione.numero %>
</p>

<% if session[:role] == 'amministrazione' && userlogged_in? %>
<%= link_to 'Edit', edit_sezione_path(@sezione) %> |
<%end%>
<%= link_to 'Back', sezioni_path %>

<p>
  <strong>Elenco alunni:</strong>
  <%= link_to 'Visualizza elenco alunni', elenco_path(:sezione_id => @sezione.id) , :style=>"color:black" %>
</p>

<% if session[:role]=='amministrazione' && userlogged_in? %>
	<p>
		<strong>Assegnazione docenti e materie:</strong>
		<%= link_to 'Assegna docenti e materie per la sezione', doc_sez_mat_path(sezione_id: @sezione.id), :style=>"color:trasparent" %>
	</p>
<% end %>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>