registro/config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#show'
  
  get "loginalunno" => "sessionealunno#new"
  get "registrazionealunno" => "alunni#new"
  post "sessionealunno/create"
  get "logoutalunno" => "sessionealunno#destroy"
  get "menualunno" => "alunni#menu"
  get "elenco" => 'alunni#elenco'
  get "assenzealunno" => "assenze/:alunno_id", to: "assenze#index"
  get "notedisciplinarialunno" => "notedisciplinari/:alunno_id", to: "notedisciplinari#index"
  get "votialunno" => "voti/:alunno_id", to: "voti#index"

  get "logindocenza" => "sessionedocenza#new"
  get "registrazionedocenza" => "docenze#new"
  post "sessionedocenza/create"
  get "logoutdocenza" => "sessionedocenza#destroy"
  get "menudocenza" => "docenze#menu"

  get "loginamministrazione" => "sessioneamministrazione#new"
  get "registrazioneamministrazione" => "amministrazioni#new"
  post "sessioneamministrazione/create"
  get "logoutamministrazione" => "sessioneamministrazione#destroy"
  get "menuamministrazione" => "amministrazioni#menu"

  get "doc_sez_mat" => "docenza_sezione_materie/:sezione_id", to: 'docenza_sezione_materie#index'
  get "nuovoinsegnamento" => "docenza_sezione_materie#nuovoinsegnamento"
  post "/alunno_attivitaextras/new"
	

  resources :alunno_attivitaextras

  resources :voti

  resources :sezioni

  resources :notedisciplinari

  resources :materie

  resources :compiti

  resources :circolari

  resources :attivitaextras

  resources :assenze

  resources :docenze

  resources :amministrazioni

  resources :alunni

  resources :docenza_sezione_materie

  resources :alunni do
    member do
      get :confirm_email
    end
  end

  resources :docenze do
    member do
      get :confirm_email
    end
  end

  resources :amministrazioni do
    member do
      get :confirm_email
    end
  end

end

registro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="menu">
     <% if userlogged_in? %>
        <% if session[:role] == 'amministrazione' %>
          <%= link_to "Menu", menuamministrazione_path %>
          <%= link_to 'Logout', logoutamministrazione_path %>
        <% elsif session[:role] == 'docenza' %>
          <%= link_to "Menu", menudocenza_path %>
          <%= link_to 'Logout', logoutdocenza_path %>
        <% else %>
          <%= link_to "Menu", menualunno_path %>
          <%= link_to 'Logout', logoutalunno_path %>
        <% end %>
     <% else %>
       <%= link_to "Home", root_path %>
     <% end %>
  </div>

 

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>