registro/config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#show'
  
  get "loginalunno" => "sessionealunno#new"
  get "registrazionealunno" => "alunni#new"
  post "sessionealunno/create"
  get "logoutalunno" => "sessionealunno#destroy"
  get "menualunno" => "alunni#menu"
  get "elenco" => 'alunni#elenco'
  get "assenzealunno" => "assenze/:alunno_id", to: "assenze#index"
  get "notedisciplinarialunno" => "notedisciplinari/:alunno_id", to: "notedisciplinari#index"
  get "votialunno" => "voti/:alunno_id", to: "voti#index"

  get "logindocenza" => "sessionedocenza#new"
  get "registrazionedocenza" => "docenze#new"
  post "sessionedocenza/create"
  get "logoutdocenza" => "sessionedocenza#destroy"
  get "menudocenza" => "docenze#menu"

  get "loginamministrazione" => "sessioneamministrazione#new"
  get "registrazioneamministrazione" => "amministrazioni#new"
  post "sessioneamministrazione/create"
  get "logoutamministrazione" => "sessioneamministrazione#destroy"
  get "menuamministrazione" => "amministrazioni#menu"

  get "doc_sez_mat" => "docenza_sezione_materie/:sezione_id", to: 'docenza_sezione_materie#index'
  get "nuovoinsegnamento" => "docenza_sezione_materie#nuovoinsegnamento"
  post "/alunno_attivitaextras/new"
	

  resources :alunno_attivitaextras

  resources :voti

  resources :sezioni

  resources :notedisciplinari

  resources :materie

  resources :compiti

  resources :circolari

  resources :attivitaextras

  resources :assenze

  resources :docenze

  resources :amministrazioni

  resources :alunni

  resources :docenza_sezione_materie

  resources :alunni do
    member do
      get :confirm_email
    end
  end

  resources :docenze do
    member do
      get :confirm_email
    end
  end

  resources :amministrazioni do
    member do
      get :confirm_email
    end
  end

end

registro/app/controllers/alunni_controller.rb
class AlunniController < ApplicationController
  before_action :set_alunno, only: [:show, :edit, :update, :destroy]
  before_filter :is_permitted, only: [:edit, :update, :destroy]

  def is_permitted
    if session[:role] == "docenza"
      redirect_to :back, :alert => "Operazione non permessa"
    end
  end

  def confirm_email
    alunno = Alunno.find_by_confirm_token(params[:id])
    if alunno
      alunno.email_activate
      flash[:success] = "Welcome! Your email has been confirmed.
      Please sign in to continue."
      redirect_to loginalunno_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  def menu
  end

  def elenco
    id=params[:sezione_id]
    @alunni=Alunno.where(sezione_id: id)
  end
  # GET /alunni
  # GET /alunni.json
  def index
    if params[:attivitaextra_id]
      @alunni = Alunno.where(id: AlunnoAttivitaextra.where(attivitaextra_id = params[:attivitaextra_id]).select("alunno_id"))
    else
      @alunni = Alunno.all
    end
  end

  # GET /alunni/1
  # GET /alunni/1.json
  def show
    @alunno=Alunno.find(params[:id])
    sez_id=@alunno.sezione_id
    if sez_id != nil
      @sezione=Sezione.find(sez_id) 
    end
  end

  # GET /alunni/new
  def new
    @sezioni = Sezione.all
    @alunno = Alunno.new
  end

  # GET /alunni/1/edit
  def edit
    @sezioni = Sezione.all
  end

  # POST /alunni
  # POST /alunni.json
  def create
    @alunno = Alunno.new(alunno_params)
    @sezioni = Sezione.all
    respond_to do |format|
      if @alunno.save
        AlunnoMailer.registration_confirmation(@alunno).deliver_now
        format.html { redirect_to @alunno, notice: 'Alunno was successfully created. Confirm your email address to continue!' }
        format.json { render :show, status: :created, location: @alunno }
      else
        format.html { render :new }
        format.json { render json: @alunno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunni/1
  # PATCH/PUT /alunni/1.json
  def update
    @sezioni = Sezione.all
    respond_to do |format|
      @alunno.user=session[:role]
      if session[:role] != "alunno"
		    alunno_params.delete(:email)
		    alunno_params.delete(:password)
		    alunno_params.delete(:password_confirmation)
      end
      if @alunno.update(alunno_params)
        format.html { redirect_to @alunno, notice: 'Alunno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alunno }
      else
        format.html { render :edit }
        format.json { render json: @alunno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunni/1
  # DELETE /alunni/1.json
  def destroy
    @alunno.destroy
    respond_to do |format|
      format.html { redirect_to alunni_url, notice: 'Alunno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alunno
      @alunno = Alunno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alunno_params
      params.require(:alunno).permit(:cf, :nome, :cognome, :indirizzo, :cittaresidenza, :cittanascita, :datanascita, :email, :password, :password_confirmation, :sezione_id)
    end
end

registro/app/helpers/alunni_helper.rb
module AlunniHelper
end

registro/app/views/alunni/_form.html.erb
<%= form_for(@alunno) do |f| %>
  <% if @alunno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alunno.errors.count, "error") %> prohibited this alunno from being saved:</h2>

      <ul>
      <% @alunno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if session[:role] == 'alunno' || session[:role]==nil %>
  <h2>Inserire dati per la registrazione:</h2>

  <div class="field">
    <%= f.label :"email" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :"conferma Password" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
<% end %>

    <h2>Inserire dati personali:</h2>

  <div class="field">
    <%= f.label :"c"%><%= f.label :"f"%><br>
    <%= f.text_field :cf %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cognome %><br>
    <%= f.text_field :cognome %>
  </div>
  <div class="field">
    <%= f.label :indirizzo %><br>
    <%= f.text_field :indirizzo %>
  </div>
  <div class="field">
    <%= f.label :"città di residenza" %><br>
    <%= f.text_field :cittaresidenza %>
  </div>
  <div class="field">
    <%= f.label :"città di nascita" %><br>
    <%= f.text_field :cittanascita %>
  </div>
  <div class="field">
    <%= f.label :"data di nascita" %><br>
    <%= f.date_select :datanascita , order: [:day, :month, :year], :use_month_names => ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Gugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre','Dicembre'], start_year: Date.today.year, end_year: Date.today.year - 100 %>
  </div>

<% if session[:role]=='amministrazione' && userlogged_in? %>
   <div class="field">
     <%= f.label :sezione_id %><br>
     <%= f.select :sezione_id, Sezione.all.collect { |p| [ "%d %s" % [p.numero, p.lettera] , p.id ] }, include_blank: true %>
   </div>
<% end %>

  <br><br>
  <div class="actions">
    <%= f.submit "Invio", :class => 'button', :style=>'background:#FFE0B2'%>
  </div>
<% end %>

 

registro/app/views/alunni/edit.html.erb
<!DOCTYPE html>
<html>
<body style="background:#FFA726;">
	<h1 style="text-align:center;">Modifica Dati</h1></div>
    <%= render 'form' %>
</body>
<%= link_to 'Show', @alunno %> |
<%= link_to 'Back', alunni_path %>
</html>

registro/app/views/alunni/elenco.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elenco Alunni</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<p id="notice"><%= notice %></p>

<body style="background:#FFA726;">
    <div class="col-md-12" style="text-align:center;">
        <h1> Elenco Alunni</h1></div>
    <div class="col-md-12">
        <div class="table-responsive", align="center">
			<table class="table", style="border-collapse:collapse;">

<thead>
				    <tr>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>CF</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Nome</span>
					  </th>

					  <th style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Cognome</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Indirizzo</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Città di residenza</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Città di nascita</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Data di nascita</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Email</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Mostra</span>
					  </th>
					  
					</tr>
<tbody>
    <% @alunni.each do |alunno| %>
      <tr>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cf %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.nome %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cognome %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.indirizzo %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cittaresidenza %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cittanascita %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.datanascita %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.email %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Show', alunno , :style=>"color:black;"%></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

registro/app/views/alunni/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elenco Alunni</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<p id="notice"><%= notice %></p>

<body style="background:#FFA726;">
    <div class="col-md-12" style="text-align:center;">
        <h1> Elenco Alunni</h1></div>
    <div class="col-md-12">
        <div class="table-responsive", align="center">
			<table class="table", style="border-collapse:collapse;">

<thead>
				    <tr>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>CF</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Nome</span>
					  </th>

					  <th style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Cognome</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Indirizzo</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Città di residenza</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Città di nascita</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Data di nascita</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Email</span>
					  </th>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Mostra</span>
					  </th>
					   <% if session[:role] != 'docenza' && userlogged_in? %>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Modifica</span>
					  </th>
					  <% end %>
					  <% if session[:role] == 'amministrazione' && userlogged_in? %>
					  <th  style="text-align:center;border:1px solid #ddd;padding:8px;">
						<span>Elimina</span>
					  </th>
					  <% end %>
					</tr>
<tbody>
    <% @alunni.each do |alunno| %>
      <tr>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cf %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.nome %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cognome %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.indirizzo %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cittaresidenza %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.cittanascita %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.datanascita %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= alunno.email %></td>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Show', alunno , :style=>"color:black;" %></td>
        <% if session[:role] != 'docenza' && userlogged_in? %>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Edit', edit_alunno_path(alunno) , :style=>"color:black;" %></td>
        <% end %>
        <% if session[:role] == 'amministrazione' && userlogged_in? %>
        <td style="text-align:center;border:1px solid #ddd;padding:8px;"><%= link_to 'Destroy', alunno , :style=>"color:black;", method: :delete, data: { confirm: 'Sei Sicuro?' } %></td>
        <%end%>      
      </tr>
    <% end %>
  </tbody>
</table>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

registro/app/views/alunni/menu.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>menuAl</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body style="background:#FFA726;">
    <div class="col-md-12">
        <h1> </h1>
    </div>
    <div class="col-md-12">
        <h1 style="text-align:center;">Menu <%if current_user.sezione_id == nil %>(sezione non ancora assegnata)<%end%></h1>
		<%if current_user.sezione_id != nil %>
        <h1> </h1>
    </div>
    <div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Visualizza compiti in classe</button>".html_safe, compiti_path, :style=>"color:black" %>
        <h3> </h3>
    </div>
    <div class="col-md-12" style="text-align:center;">		
        <%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Visualizza attività extrascolastiche</button>".html_safe, attivitaextras_path, :style=>"color:black" %>
        <h3> </h3>
    </div>
    <%end%>
    <div class="col-md-12" style="text-align:center;">
         <%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Visualizza docenti</button>".html_safe, docenze_path, :style=>"color:black" %>
        <h3> </h3>
    </div>
    <div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Visualizza circolari</button>".html_safe, circolari_path, :style=>"color:black" %>
		<h3> </h3>
    </div>

    <div class="col-md-12" style="text-align:center;">
		<%= link_to "<button class='btn btn-default btn-lg', style='background:#FFE0B2;font-size:x-large;height:30px;width:400px;'>Visualizza profilo</button>".html_safe, alunno_path(current_user.id), :style=>"color:black" %>
        <h1> </h1>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

registro/app/views/alunni/new.html.erb
<!DOCTYPE html>
<html>
<body style="background:#FFA726;">
	<h1 style="text-align:center;">Nuovo Alunno</h1></div>
    <%= render 'form' %>
</body>
<%= link_to 'Back', alunni_path %>
</html>

registro/app/views/alunni/show.html.erb
<!DOCTYPE html>
<html>
<body style="background:#FFA726;">
<p id="notice"><%= notice %></p>

<p>
  <h1 style="text-align:center;">Dati Registrati </h1>
  <h2>Dati Personali </h2>
  <strong>CF:</strong>
  <%= @alunno.cf %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @alunno.nome %>
</p>

<p>
  <strong>Cognome:</strong>
  <%= @alunno.cognome %>
</p>

<p>
  <strong>Indirizzo:</strong>
  <%= @alunno.indirizzo %>
</p>

<p>
  <strong>Città di residenza:</strong>
  <%= @alunno.cittaresidenza %>
</p>

<p>
  <strong>Città di nascita:</strong>
  <%= @alunno.cittanascita %>
</p>

<p>
  <strong>Data di nascita:</strong>
  <%= @alunno.datanascita %>
</p>

<p>
  <strong>Sezione:</strong>
  <% if @sezione != nil %>
   <%= @sezione.numero %>
   <%= @sezione.lettera %>
  <% else %>
   <%= "Non assegnato" %>
  <% end %>
</p>

<p>
  <h2>Dati Registrazione </h2>
  <strong>Email:</strong>
  <%= @alunno.email %>
</p>

<p>
  <strong>Password: ******</strong>
  <%= @alunno.password %>
</p>


<div>
	<%if session[:role]!="alunno" || current_user.sezione_id != nil %>
		<%= link_to "<button class='btn btn-default', style='background:#FFE0B2;width:150px;'>Visualizza assenze</button>".html_safe, assenzealunno_path(alunno_id: @alunno.id), :style=>"color:black" %>
		<h3> </h3>
	<%end%>

</div>

<div>	
	<%= link_to "<button class='btn btn-default', style='background:#FFE0B2; width:150px;'>Note Disciplinari</button>".html_safe, notedisciplinarialunno_path(alunno_id: @alunno.id), :style=>"color:black" %>
	<h3> </h3>
</div>

<div>
	<%= link_to "<button class='btn btn-default', style='background:#FFE0B2;width:150px;'>Voti</button>".html_safe, votialunno_path(alunno_id: @alunno.id), :style=>"color:black" %>
	<h3> </h3>
</div>

<% if session[:role] != 'docenza' && userlogged_in? %>
  <%= link_to 'Edit', edit_alunno_path(@alunno) %>
  <%= link_to 'Destroy', @alunno, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
  <%= link_to 'Login', loginalunno_path %>
<% end %>